#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Diego\ExcelConverter\ConvertCommand());
$application->setDefaultCommand('convert', true);
$application->run();
